### ISSUE TITLE
Documentation not complete

### ISSUE THREAD

**Issue by OstlerDev** [florincoin/florincoin#9]
It is unclear the differences between `comment`'s and `tx-comment`'s inside the API, I had to search through the code to find this. Is there a way for this to be made more distinct or visible?

The code I am referencing can be found here: https://github.com/florincoin/florincoin/blob/master-0.10/src/rpcwallet.cpp#L347

**Comment by florincoin** [comment]
Updated rpc help to include tx-comment description, e.g.

florincoin-cli help sendtoaddress

...
5. "tx-comment" (string, optional) A transaction comment. This comment is stored in the blockchain and is public.
